# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcc.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from controller import ConnectCRBM
from controller2 import EvolutionaryAlgorithm
from PandasLoadPyqt5 import PandasModel
import pandas as pd
from dialog import Ui_Dialog as Form
#from dialog2 import ApplicationWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 948)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 12, 0, 1, 1)
        self.pbias_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pbias_input.setObjectName("pbias_input")
        self.gridLayout_2.addWidget(self.pbias_input, 4, 1, 1, 1)
        self.batch_input = QtWidgets.QSpinBox(self.groupBox)
        self.batch_input.setObjectName("batch_input")
        self.gridLayout_2.addWidget(self.batch_input, 13, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.epsilon_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.epsilon_input.setObjectName("epsilon_input")
        self.gridLayout_2.addWidget(self.epsilon_input, 8, 1, 1, 1)
        self.epoch_per_layer_input = QtWidgets.QSpinBox(self.groupBox)
        self.epoch_per_layer_input.setObjectName("epoch_per_layer_input")
        self.gridLayout_2.addWidget(self.epoch_per_layer_input, 12, 1, 1, 1)
        self.sigma_stop_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sigma_stop_input.setObjectName("sigma_stop_input")
        self.gridLayout_2.addWidget(self.sigma_stop_input, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.pbias_lambda_input = QtWidgets.QSpinBox(self.groupBox)
        self.pbias_lambda_input.setObjectName("pbias_lambda_input")
        self.gridLayout_2.addWidget(self.pbias_lambda_input, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 1)
        self.regL2_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.regL2_input.setObjectName("regL2_input")
        self.gridLayout_2.addWidget(self.regL2_input, 7, 1, 1, 1)
        self.vbias_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.vbias_input.setObjectName("vbias_input")
        self.gridLayout_2.addWidget(self.vbias_input, 6, 1, 1, 1)
        self.sigma_start_input = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sigma_start_input.setObjectName("sigma_start_input")
        self.gridLayout_2.addWidget(self.sigma_start_input, 9, 1, 1, 1)
        self.CD_steps_input = QtWidgets.QSpinBox(self.groupBox)
        self.CD_steps_input.setObjectName("CD_steps_input")
        self.gridLayout_2.addWidget(self.CD_steps_input, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 10, 0, 1, 1)
        self.dataset_input = QtWidgets.QComboBox(self.groupBox)
        self.dataset_input.setObjectName("dataset_input")
        self.dataset_input.addItem("")
        self.dataset_input.addItem("")
        self.dataset_input.addItem("")
        self.dataset_input.addItem("")
        self.gridLayout_2.addWidget(self.dataset_input, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.num_bases_input = QtWidgets.QSpinBox(self.groupBox)
        self.num_bases_input.setObjectName("num_bases_input")
        self.gridLayout_2.addWidget(self.num_bases_input, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.blocksize_1 = QtWidgets.QSpinBox(self.groupBox)
        self.blocksize_1.setObjectName("blocksize_1")
        self.horizontalLayout_2.addWidget(self.blocksize_1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.blocksize2 = QtWidgets.QSpinBox(self.groupBox)
        self.blocksize2.setObjectName("blocksize2")
        self.horizontalLayout_2.addWidget(self.blocksize2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filtersize_1 = QtWidgets.QSpinBox(self.groupBox)
        self.filtersize_1.setObjectName("filtersize_1")
        self.horizontalLayout.addWidget(self.filtersize_1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.filtersize_2 = QtWidgets.QSpinBox(self.groupBox)
        self.filtersize_2.setObjectName("filtersize_2")
        self.horizontalLayout.addWidget(self.filtersize_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.exec_network = QtWidgets.QPushButton(self.frame_2)
        self.exec_network.setObjectName("exec_network")
        self.gridLayout_10.addWidget(self.exec_network, 5, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_3 = QtWidgets.QWidget(self.frame_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_26.addWidget(self.label_22, 0, 0, 1, 1)
        self.weights_img = QtWidgets.QLabel(self.widget_3)
        self.weights_img.setText("")
        self.weights_img.setPixmap(QtGui.QPixmap("results/weights.jpg"))
        self.weights_img.setScaledContents(True)
        self.weights_img.setObjectName("weights_img")
        self.gridLayout_26.addWidget(self.weights_img, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_27.addWidget(self.label_7, 1, 0, 1, 1)
        self.pooling_img = QtWidgets.QLabel(self.widget_4)
        self.pooling_img.setText("")
        self.pooling_img.setPixmap(QtGui.QPixmap("results/-poooling.jpg"))
        self.pooling_img.setScaledContents(True)
        self.pooling_img.setObjectName("pooling_img")
        self.gridLayout_27.addWidget(self.pooling_img, 2, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_4, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_49 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_25.addWidget(self.label_49, 0, 0, 1, 1)
        self.neg_img = QtWidgets.QLabel(self.widget_2)
        self.neg_img.setText("")
        self.neg_img.setPixmap(QtGui.QPixmap("results/neg_data.jpg"))
        self.neg_img.setScaledContents(True)
        self.neg_img.setObjectName("neg_img")
        self.neg_img.setMargin(28)
        self.gridLayout_25.addWidget(self.neg_img, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setObjectName("widget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_20 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_16.addWidget(self.label_20, 0, 0, 1, 1)
        self.pos_img = QtWidgets.QLabel(self.widget)
        self.pos_img.setText("")
        self.pos_img.setPixmap(QtGui.QPixmap("results/pos_data.jpg"))
        self.pos_img.setScaledContents(True)
        self.pos_img.setObjectName("pos_img")
        self.pos_img.setMargin(28)
        self.gridLayout_16.addWidget(self.pos_img, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_3, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 2, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 411, 343))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.progress_area = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.progress_area.setObjectName("progress_area")
        self.gridLayout_14.addWidget(self.progress_area, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.addWidget(self.scrollArea_3, 4, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 0, 0, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(self.frame_2)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout_10.addWidget(self.progress_bar, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 10, 0, 1, 1)
        self.mh_pbiaslambda_input = QtWidgets.QSpinBox(self.groupBox_3)
        self.mh_pbiaslambda_input.setObjectName("mh_pbiaslambda_input")
        self.gridLayout_8.addWidget(self.mh_pbiaslambda_input, 3, 1, 1, 1)
        self.mh_vbias_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_vbias_input.setObjectName("mh_vbias_input")
        self.gridLayout_8.addWidget(self.mh_vbias_input, 4, 1, 1, 1)
        self.mh_regL2_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_regL2_input.setObjectName("mh_regL2_input")
        self.gridLayout_8.addWidget(self.mh_regL2_input, 5, 1, 1, 1)
        self.mh_sigmastop_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_sigmastop_input.setObjectName("mh_sigmastop_input")
        self.gridLayout_8.addWidget(self.mh_sigmastop_input, 8, 1, 1, 1)
        self.mh_epochperlayer_input = QtWidgets.QSpinBox(self.groupBox_3)
        self.mh_epochperlayer_input.setObjectName("mh_epochperlayer_input")
        self.gridLayout_8.addWidget(self.mh_epochperlayer_input, 9, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.mh_sigmastart_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_sigmastart_input.setObjectName("mh_sigmastart_input")
        self.gridLayout_8.addWidget(self.mh_sigmastart_input, 7, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 5, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_3)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 8, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 6, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mh_blockshape1_input = QtWidgets.QSpinBox(self.groupBox_3)
        self.mh_blockshape1_input.setObjectName("mh_blockshape1_input")
        self.horizontalLayout_3.addWidget(self.mh_blockshape1_input)
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_3.addWidget(self.label_48)
        self.mh_blockshape2_input = QtWidgets.QSpinBox(self.groupBox_3)
        self.mh_blockshape2_input.setObjectName("mh_blockshape2_input")
        self.horizontalLayout_3.addWidget(self.mh_blockshape2_input)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 7, 0, 1, 1)
        self.mh_epsilon_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_epsilon_input.setObjectName("mh_epsilon_input")
        self.gridLayout_8.addWidget(self.mh_epsilon_input, 6, 1, 1, 1)
        self.mh_batch_input = QtWidgets.QSpinBox(self.groupBox_3)
        self.mh_batch_input.setObjectName("mh_batch_input")
        self.gridLayout_8.addWidget(self.mh_batch_input, 10, 1, 1, 1)
        self.mh_dataset_input = QtWidgets.QComboBox(self.groupBox_3)
        self.mh_dataset_input.setObjectName("mh_dataset_input")
        self.mh_dataset_input.addItem("")
        self.mh_dataset_input.addItem("")
        self.mh_dataset_input.addItem("")
        self.mh_dataset_input.addItem("")
        self.gridLayout_8.addWidget(self.mh_dataset_input, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 9, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 1, 0, 1, 1)
        self.mh_pbias_input = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.mh_pbias_input.setObjectName("mh_pbias_input")
        self.gridLayout_8.addWidget(self.mh_pbias_input, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 0, 1, 1)
        self.alg_metaheuristic_input = QtWidgets.QComboBox(self.groupBox_2)
        self.alg_metaheuristic_input.setObjectName("alg_metaheuristic_input")
        self.alg_metaheuristic_input.addItem("")
        self.alg_metaheuristic_input.addItem("")
        self.gridLayout_6.addWidget(self.alg_metaheuristic_input, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 4, 0, 1, 1)
        self.pcrossover_input = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pcrossover_input.setObjectName("pcrossover_input")
        self.gridLayout_6.addWidget(self.pcrossover_input, 1, 1, 1, 1)
        self.pmutation_input = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pmutation_input.setObjectName("pmutation_input")
        self.gridLayout_6.addWidget(self.pmutation_input, 2, 1, 1, 1)
        self.pop_size_input = QtWidgets.QSpinBox(self.groupBox_2)
        self.pop_size_input.setObjectName("pop_size_input")
        self.gridLayout_6.addWidget(self.pop_size_input, 3, 1, 1, 1)
        self.gen_size_input = QtWidgets.QSpinBox(self.groupBox_2)
        self.gen_size_input.setObjectName("gen_size_input")
        self.gridLayout_6.addWidget(self.gen_size_input, 4, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_37 = QtWidgets.QLabel(self.frame_5)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 411, 343))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.progressArea2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.progressArea2.setObjectName("progressArea2")
        self.gridLayout_12.addWidget(self.progressArea2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_11.addWidget(self.scrollArea, 4, 0, 1, 1)
        self.exec_opt = QtWidgets.QPushButton(self.frame_5)
        self.exec_opt.setObjectName("exec_opt")
        self.gridLayout_11.addWidget(self.exec_opt, 5, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 411, 343))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableResults = QtWidgets.QTableView(self.scrollAreaWidgetContents_2)
        self.tableResults.setObjectName("tableResults")
        self.gridLayout_13.addWidget(self.tableResults, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.progressBar2 = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar2.setProperty("value", 0)
        self.progressBar2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar2.setObjectName("progressBar2")
        self.gridLayout_11.addWidget(self.progressBar2, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 0, 1, 3, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.b_cdsteps_min = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_cdsteps_min.setObjectName("b_cdsteps_min")
        self.gridLayout_7.addWidget(self.b_cdsteps_min, 3, 1, 1, 1)
        self.b_group_min = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_group_min.setObjectName("b_group_min")
        self.gridLayout_7.addWidget(self.b_group_min, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 1, 0, 1, 1)
        self.b_group_max = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_group_max.setObjectName("b_group_max")
        self.gridLayout_7.addWidget(self.b_group_max, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 2, 1, 1)
        self.b_filtersize_min = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_filtersize_min.setObjectName("b_filtersize_min")
        self.gridLayout_7.addWidget(self.b_filtersize_min, 2, 1, 1, 1)
        self.b_filtersize_max = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_filtersize_max.setObjectName("b_filtersize_max")
        self.gridLayout_7.addWidget(self.b_filtersize_max, 2, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 0, 1, 1, 1)
        self.b_cdsteps_max = QtWidgets.QSpinBox(self.groupBox_4)
        self.b_cdsteps_max.setObjectName("b_cdsteps_max")
        self.gridLayout_7.addWidget(self.b_cdsteps_max, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Convolutional Restricted Boltzmann Machine "))
        self.label_15.setText(_translate("MainWindow", "CD steps"))
        self.label_4.setText(_translate("MainWindow", "Block size"))
        self.label_17.setText(_translate("MainWindow", "Batch size"))
        self.label_3.setText(_translate("MainWindow", "Filter size"))
        self.label_16.setText(_translate("MainWindow", "Epoch"))
        self.label_6.setText(_translate("MainWindow", "Step size towards sparsity equilibrium"))
        self.label_8.setText(_translate("MainWindow", "Initial value for visible bias"))
        self.label_11.setText(_translate("MainWindow", "Sigma start"))
        self.label.setText(_translate("MainWindow", "Dataset"))
        self.label_12.setText(_translate("MainWindow", "Sigma stop"))
        self.dataset_input.setItemText(0, _translate("MainWindow", "MNIST"))
        self.dataset_input.setItemText(1, _translate("MainWindow", "Caltech 101 Silhouettes"))
        self.dataset_input.setItemText(2, _translate("MainWindow", "MPEG"))
        self.dataset_input.setItemText(3, _translate("MainWindow", "Semeion"))
        self.label_5.setText(_translate("MainWindow", "Sparsity parameter"))
        self.label_2.setText(_translate("MainWindow", "Groups"))
        self.label_10.setText(_translate("MainWindow", "Learning rate"))
        self.label_9.setText(_translate("MainWindow", "Regularization L2"))
        self.label_18.setText(_translate("MainWindow", "X"))
        self.label_13.setText(_translate("MainWindow", "X"))
        self.exec_network.setText(_translate("MainWindow", "Run"))
        self.label_22.setText(_translate("MainWindow", "Weights"))
        self.label_7.setText(_translate("MainWindow", "Pooling units"))
        self.label_49.setText(_translate("MainWindow", "Negative data"))
        self.label_20.setText(_translate("MainWindow", "Positive data"))
        self.label_14.setText(_translate("MainWindow", "Progress"))
        self.label_45.setText(_translate("MainWindow", "Images"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Example CRBM"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fixed hyperparameters"))
        self.label_36.setText(_translate("MainWindow", "Batch size"))
        self.label_44.setText(_translate("MainWindow", "Sparsity parameter"))
        self.label_42.setText(_translate("MainWindow", "Dataset"))
        self.label_47.setText(_translate("MainWindow", "Regularization L2"))
        self.label_43.setText(_translate("MainWindow", "Sigma stop"))
        self.label_46.setText(_translate("MainWindow", "Learning rate"))
        self.label_40.setText(_translate("MainWindow", "Initial value for visible bias"))
        self.label_48.setText(_translate("MainWindow", "X"))
        self.label_41.setText(_translate("MainWindow", "Sigma start"))
        self.mh_dataset_input.setItemText(0, _translate("MainWindow", "MNIST"))
        self.mh_dataset_input.setItemText(1, _translate("MainWindow", "Caltech 101 Silhouettes"))
        self.mh_dataset_input.setItemText(2, _translate("MainWindow", "MPEG"))
        self.mh_dataset_input.setItemText(3, _translate("MainWindow", "Semeion"))
        self.label_39.setText(_translate("MainWindow", "Step size towards sparsity equilibrium"))
        self.label_34.setText(_translate("MainWindow", "Epoch"))
        self.label_35.setText(_translate("MainWindow", "Block size"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.label_25.setText(_translate("MainWindow", "Probability of crossover"))
        self.label_23.setText(_translate("MainWindow", "Meta-Heuristic "))
        self.alg_metaheuristic_input.setItemText(0, _translate("MainWindow", "Genetic Algorithm"))
        self.alg_metaheuristic_input.setItemText(1, _translate("MainWindow", "Genetic Programming"))
        self.label_26.setText(_translate("MainWindow", "Probability of mutation"))
        self.label_27.setText(_translate("MainWindow", "Population"))
        self.label_28.setText(_translate("MainWindow", "Number of generations"))
        self.label_37.setText(_translate("MainWindow", "Progress"))
        self.label_38.setText(_translate("MainWindow", "Results"))
        self.exec_opt.setText(_translate("MainWindow", "Run"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Hyperparameters -  bound"))
        self.label_29.setText(_translate("MainWindow", "Groups"))
        self.label_31.setText(_translate("MainWindow", "CD steps"))
        self.label_30.setText(_translate("MainWindow", "Filter size"))
        self.label_33.setText(_translate("MainWindow", "Max"))
        self.label_32.setText(_translate("MainWindow", "Min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Genetic Algorithm / Genetic Programming"))


        self.num_bases_input.setValue(25)
        self.filtersize_1.setValue(11)
        self.filtersize_2.setValue(11)
        self.blocksize_1.setValue(2)
        self.blocksize2.setValue(2)
        self.pbias_input.setDecimals(3)
        self.pbias_input.setValue(0.05)
        self.pbias_lambda_input.setValue(5)
        self.vbias_input.setDecimals(3)
        self.vbias_input.setValue(0.001)
        self.regL2_input.setDecimals(3)
        self.regL2_input.setValue(0.01)
        self.epsilon_input.setDecimals(3)
        self.epsilon_input.setValue(0.1)
        self.sigma_start_input.setValue(0.2)
        self.sigma_stop_input.setValue(0.1)
        self.CD_steps_input.setValue(1)
        self.epoch_per_layer_input.setValue(20)
        self.batch_input.setRange(1,1000)
        self.batch_input.setValue(100)
        self.progress_bar.setMinimum(0)
        
        self.pcrossover_input.setValue(0.4)
        self.pmutation_input.setValue(0.1)
        self.pop_size_input.setValue(30)
        self.gen_size_input.setValue(6)
        
        self.b_group_min.setValue(1)
        self.b_group_max.setValue(25)
        self.b_filtersize_min.setValue(5)
        self.b_filtersize_max.setValue(15)
        self.b_cdsteps_min.setValue(1)
        self.b_cdsteps_max.setValue(3)
        
        self.mh_blockshape1_input.setValue(2)
        self.mh_blockshape2_input.setValue(2)
        self.mh_pbias_input.setDecimals(3)
        self.mh_pbias_input.setValue(0.05)
        self.mh_pbiaslambda_input.setValue(5)
        self.mh_vbias_input.setDecimals(3)
        self.mh_vbias_input.setValue(0.001)
        self.mh_regL2_input.setDecimals(3)
        self.mh_regL2_input.setValue(0.01)
        self.mh_epsilon_input.setDecimals(3)
        self.mh_epsilon_input.setValue(0.1)
        self.mh_sigmastart_input.setValue(0.2)
        self.mh_sigmastop_input.setValue(0.1)
        self.mh_epochperlayer_input.setValue(20)
        self.mh_batch_input.setRange(1,1000)
        self.mh_batch_input.setValue(100)
        
        self.exec_network.clicked.connect(self.run_CRBM)
        self.exec_opt.clicked.connect(self.run_AE)

    def open_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Form()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()        
    
    
    def run_AE(self):
        
        pick_dataset = self.mh_dataset_input.currentText()
        pick_algorithm= self.alg_metaheuristic_input.currentText()
        
        model={
               # shape of the window used for max pooling
               'block_shape': ( self.mh_blockshape1_input.value(), self.mh_blockshape2_input.value() ),
                                
               # sparsity parameter - expected activations of the hidden units
               'pbias': self.mh_pbias_input.value(), 
               # step size towards sparsity equilibrium
               'pbias_lambda': self.mh_pbiaslambda_input.value(),  
                    
               # initial value for the hiden bias
               'init_bias': 0.01,
               # initial value for visible bias
               'vbias': self.mh_vbias_input.value(),
               # regularization factor to keep the length of weight vector small
               'regL2': self.mh_regL2_input.value() ,
               # learning rate - the ratio of change taken from gradient descent
               'epsilon': self.mh_epsilon_input.value(),
               # start and stop value of the parameter used to control the effect 
               # of input vector (versus bias)
                'sigma_start': self.mh_sigmastart_input.value(),
                'sigma_stop': self.mh_sigmastop_input.value(),
                # -- number of epochs to learn each layer after all previous layers are
                # learned
                'epoch_per_layer': self.mh_epochperlayer_input.value(),
                'batch': self.mh_batch_input.value(),
               }
        
        #Bound (down,up)
        bound = {   "num_bases" : (self.b_group_min.value(), self.b_group_max.value(), int),
                    "btmup_window_shape" : (self.b_filtersize_min.value(), self.b_filtersize_max.value(), int),
                    "CD_steps" : (self.b_cdsteps_min.value(), self.b_cdsteps_max.value(), int )}
        
        parameters_ea = { "p_cx":self.pcrossover_input.value(),
                          "p_mut":self.pmutation_input.value(),
                          "n_pop":self.pop_size_input.value(),
                          "n_gen":self.gen_size_input.value() }
        
        t= EvolutionaryAlgorithm(model,bound,parameters_ea,pick_dataset,pick_algorithm)
        t.run(self.progressArea2, self.progressBar2, self.tableResults)


        
        
    def run_CRBM(self):
        #self.progress_area.setTextBackgroundColor()
        #self.progress_area.append('ola')
        
        pick_dataset = self.dataset_input.currentText()
        
        model={
               # -- number of bases or "groups" in the layer - equivalent to 
               #       parameter K in the Lee et. al. ICML09 paper 5
               'num_bases': self.num_bases_input.value(),
               # shape of the bottom-up filter 10,10
               'btmup_window_shape': (self.filtersize_1.value() , self.filtersize_2.value()),
               # shape of the window used for max pooling
               'block_shape': (self.blocksize_1.value(), self.blocksize2.value()),
                                
               # sparsity parameter - expected activations of the hidden units
               'pbias': self.pbias_input.value(), 
               # step size towards sparsity equilibrium
               'pbias_lambda': self.pbias_lambda_input.value(),  
                    
               # initial value for the hiden bias
               'init_bias': 0.01,
               # initial value for visible bias
               'vbias': self.vbias_input.value(),
               # regularization factor to keep the length of weight vector small
               'regL2': self.regL2_input.value(),
               # learning rate - the ratio of change taken from gradient descent
               'epsilon': self.epsilon_input.value(),
               # start and stop value of the parameter used to control the effect 
               # of input vector (versus bias)
                'sigma_start': self.sigma_start_input.value(),
                'sigma_stop': self.sigma_stop_input.value(),
                # -- number of steps (loops) performed in the contrastive
                # divergence algorithm
                'CD_steps': self.CD_steps_input.value(),
                # -- number of epochs to learn each layer after all previous layers are
                # learned
                'epoch_per_layer': self.epoch_per_layer_input.value(),
                'batch':self.batch_input.value(),
               }
        
        t = ConnectCRBM(model, pick_dataset)
        t.train(self.progress_area, self.progress_bar ,self.pos_img,self.neg_img,self.weights_img,self.pooling_img)
        
        self.open_dialog()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
